User Inventory changes
XRFoundation/XREngine pull request #3876
Opened 2021-10-27 12:12 UTC by swpnit82

Please review and merge user inventory changes

2021-10-30 10:44 UTC, kinjalravel commented
@swpnit82  For user and inventory item association it should need to return actual items details not it's association ids, I will send updated API

2021-10-30 11:22 UTC, HexaField commented
Let's get some basic tests with mock data before we pull this in.

2021-10-30 17:13 UTC, swpnit82 commented
We are working on testcases

2021-11-10 22:39 UTC, HexaField requested changes

2021-11-10 22:39 UTC, HexaField commented on packages/server-core/src/user/inventory-item/inventory-item.model.ts
> +    ;(inventoryItem as any).hasMany(models.user_trade, { foreignKey: 'fromInventoryItemId1', required: true })
this is definitely not the right way to implement this. this should only have one association with user_trade

2021-11-10 22:41 UTC, HexaField requested changes

2021-11-10 22:41 UTC, HexaField commented on packages/server-core/src/user/user-trade/user-trade.hooks.ts
> +import app from "../../../../server/src/app"
`server-core` cannot import from `server` package

2021-11-10 22:41 UTC, HexaField commented on packages/server-core/src/user/user-trade/user-trade.model.ts
> +export default (app: Application): any => {
why do we need to store user trade in the database? this should just be a feathers service rather than a feathers-sequelize service & model

2021-12-03 02:22 UTC, closed without merging