Wordpress & WooCommerce Implementation
XRFoundation/XREngine pull request #3941
Opened 2021-11-02 23:01 UTC by rondoor124

This is the initial version of the WooCommerce element.
[#3135](https://github.com/XRFoundation/XREngine/issues/3135)

2021-11-18 00:00 UTC, speigg commented
@rondoor124 is this still a draft?

2021-11-19 16:26 UTC, rondoor124 commented
Hi @speigg, this branch is ready for the QA, I will host the WordPress site somewhere and push the world file soon,

2021-11-19 17:43 UTC, rondoor124 commented on woocommerce.world
> +{"version":4,"root":"2266BED7-6CC4-48A6-95DD-9BCD3CF9EAFC","entities":{"2266BED7-6CC4-48A6-95DD-9BCD3CF9EAFC":{"name":"empty_scene","components":[{"name":"mtdata","props":{"meta_data":""}},{"name":"f
This is the Woocommerce world file. Please be careful about the CORS when fetching the assets.

2021-11-19 17:44 UTC, rondoor124 commented
Hi, @speigg This PR is ready for review. Thanks.

2021-11-21 23:14 UTC, speigg commented
We need to find a solution for this 
<img width="698" alt="Screen Shot 2021-11-21 at 6 12 49 PM" src="https://user-images.githubusercontent.com/507127/142782741-b1e53d70-8d4d-4e64-974f-f80eb6d23001.png">

2021-12-07 03:01 UTC, speigg approved these changes

2021-12-07 03:12 UTC, speigg commented
@rondoor124  Just a couple merge conflicts w/ dev. Can you fix that, and then I'll merge this in? Thanks!

2021-12-07 04:12 UTC, HexaField requested changes
We can simplify the shopify and woocommerce scene loaded cases by removing them entirely and changing the json data to use the image, video, gltf-model components directly, serialising them on an as-needed basis in the node editors. We have optimizations being made in [this PR](https://github.com/XRFoundation/XREngine/pull/4248) which will make these entirely composable (including editor nodes) so we will have no duplicated code in the codebase anywhere. It is fine for now, but lets try and keep the scene loader as simple as possible.

We can also remove the cors wrapper in loadGLTFModel where the conflict exists.

2021-12-07 04:26 UTC, HexaField requested changes

2021-12-07 04:26 UTC, HexaField commented on packages/engine/src/scene/classes/Video.ts
> +        this.el.src = corsAnywhereUrl(this._src)
no longer necessary

2021-12-07 04:26 UTC, HexaField commented on packages/engine/src/assets/functions/loadTexture.ts
> +    textureLoader.load(corsAnywhereUrl(src), resolve, null, (error) =>
no longer necessary

2021-12-07 04:26 UTC, HexaField commented on packages/engine/src/assets/functions/LoadGLTF.ts
> +      corsAnywhereUrl(url),
no longer necessary

2021-12-07 04:26 UTC, HexaField commented on packages/client-core/src/util/cors.tsx
> +export const corsAnywhereUrl = (url) => {
this file can be removed

2021-12-07 04:26 UTC, HexaField commented on .env.local.default
> +VITE_CORS_SERVER_PORT=3035
no longer necessary

2021-12-07 04:26 UTC, HexaField commented on packages/editor/src/nodes/WooCommerceNode.ts
> +      this.extendNode.src = corsAnywhereUrl(media.url)
no longer necessary

2021-12-07 04:26 UTC, HexaField commented on packages/editor/src/nodes/WooCommerceNode.ts
> +    await this.extendNode.load(corsAnywhereUrl(media.url))
no longer necessary

2021-12-07 04:26 UTC, HexaField commented on packages/engine/src/scene/functions/loadGLTFModel.ts
> +          url: corsAnywhereUrl(component.data.src),
no longer necessary

2021-12-07 04:26 UTC, HexaField commented on packages/ops/xrengine/templates/api-server-ingress.yaml
> +{{- $corsSvcPort := .Values.api.service.corsServerPort -}}
please ensure this is merged correctly

2021-12-07 04:26 UTC, HexaField commented on packages/projects/default-project/wooCommerce.scene.json
> +  "entities": {
lets not worry about a new scene for now, we are already showing off shopify intergration

2021-12-11 03:20 UTC, HexaField approved these changes

2021-12-11 03:21 UTC, merged