Review all hookstate and feathers typings
XRFoundation/XREngine pull request #3959
Opened 2021-11-03 12:19 UTC by kimenyikevin

Github [issue](https://github.com/XRFoundation/XREngine/issues/3955)

2021-11-05 03:18 UTC, speigg approved these changes

2021-11-05 04:10 UTC, HexaField approved these changes

2021-11-05 05:54 UTC, barankyle commented
I don't want to merge this in until the sub-states that were improperly combined, like the four different user states from UserService, are split into separate services.

2021-11-05 05:56 UTC, barankyle requested changes
I don't want to merge this in until the substates that were improperly merged together, like the four different ones in UserService, are split into separate services.

2021-11-09 05:40 UTC, barankyle approved these changes

2021-11-09 05:46 UTC, merged