Network Ownership on Client Sends Outgoing Pose
XRFoundation/XREngine pull request #4133
Opened 2021-11-16 23:23 UTC by HexaField

## Summary

owned objects now send their pose from the client

## Checklist
- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] Changes have been manually QA'd 
- [ ] Changes reviewed by at least 2 approved reviewers

## References

References to pertaining issue(s)

## Reviewers

@speigg @NateTheGreatt

2021-11-16 23:24 UTC, NateTheGreatt approved these changes

2021-11-16 23:24 UTC, speigg approved these changes

2021-11-17 00:12 UTC, NateTheGreatt requested changes

2021-11-17 00:12 UTC, NateTheGreatt commented on packages/engine/tests/networking/systems/OutgoingNetworkSystem.test.ts
>          // make first entity the client's entity
we should rename this test and buff it before merging to cover these changes

`should only queue client-owned state changes on client`
- assert that more than one client-owned object's state is queued

2021-11-17 00:56 UTC, NateTheGreatt approved these changes
lgtm!

2021-11-17 00:58 UTC, merged