Source AppConfig From DB
XRFoundation/XREngine pull request #4357
Opened 2021-12-02 14:05 UTC by zulqarnainhanif

## Summary

use config from db for analytics, game-server and server-core workspace

## Checklist
- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## References

[References to pertaining issue(s)](https://github.com/XRFoundation/XREngine/issues/4299)

## QA Steps

1. `git checkout pr_branch_name`
2. `npm install`
3. `npm run dev-reinit`
4. `npm run dev`

List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos.

## Reviewers

@HexaField @barankyle

2021-12-11 02:36 UTC, rondoor124 commented
Hi @zulqarnainhanif  @barankyle 
So I would like to move this [pem file](https://github.com/XRFoundation/XREngine/pull/4423/files#diff-fc461757101c0a3bfa1c7c5b1bd17dbc296785124584e6d61bfee5a879aa89a3R13) and some GitHub [certs](https://github.com/XRFoundation/XREngine/pull/4423/files#diff-fc461757101c0a3bfa1c7c5b1bd17dbc296785124584e6d61bfee5a879aa89a3R124) into the Database.
The pem file is actually a 4096 bytes string file and we need to read it from [here](https://github.com/XRFoundation/XREngine/pull/4423/files#diff-33f0167016721cfe6302b67b36443ff8f9850da6336a2bb2d15523791450fc5eR24) as a string 

Please kindly let me know if you have any questions about it.
Thanks.

2021-12-13 21:30 UTC, HexaField requested changes

2021-12-13 21:30 UTC, HexaField commented on packages/analytics/src/collect-analytics.ts
> +    const app = createApp()
this will create a new app each time, this should be scoped outside of the setInterval

2021-12-13 21:30 UTC, HexaField commented on packages/analytics/src/updateAppConfig.ts
> +import dotenv from 'dotenv'
we we should centralise this file and the one in gameserver into appconfig.ts itself such that it is self contained

2021-12-14 07:56 UTC, barankyle approved these changes

2021-12-14 08:08 UTC, merged