Engine events refactor
XRFoundation/XREngine pull request #4360
Opened 2021-12-03 03:30 UTC by Abhishek-Pathak-Here

## Summary

A summary of changes being made in this PR

## Checklist
- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## References

References to pertaining issue(s)

## QA Steps

1. `git checkout pr_branch_name`
2. `npm install`
3. `npm run dev-reinit`
4. `npm run dev`

List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos.

## Reviewers

@HexaField @speigg @NateTheGreatt

2021-12-06 23:54 UTC, speigg commented
Some high-level feedback; all of these receptors you are writing should not be using `matchesFromAny`, just `matches`. `matchesFromAny` is responding to actions that originate from non-trusted sources (naturally, locally dispatched actions are always trusted).

2021-12-15 23:53 UTC, HexaField requested changes
Could you please do a thourough test using /location/sky-station to ensure things like multiplayer physics, equippables, video chat, and generally all the functionality is working correctly.

2021-12-16 10:51 UTC, HexaField requested changes

2021-12-16 10:51 UTC, HexaField commented on packages/client/src/components/World/LoadEngineWithScene.tsx
> +    const slugifiedName = locationState.currentLocation.location.slugifiedName.value
this is incorrect merging, please revert this

2021-12-16 10:51 UTC, HexaField commented on packages/client/src/components/World/LoadEngineWithScene.tsx
> +      dispatchLocal(EngineActions.setTeleporting(null!) as any)
incorrect merge, please revert

2021-12-16 10:51 UTC, HexaField commented on packages/client/src/components/World/LocationLoadHelper.tsx
> +export const teleportToLocation = async (
incorrect merge, please remove this fucntion

2021-12-17 01:39 UTC, HexaField approved these changes

2021-12-17 01:42 UTC, merged

2021-12-17 01:42 UTC, HexaField commented
Great work!