Inventory Trading Wallet Menus
XRFoundation/XREngine pull request #4438
Opened 2021-12-10 17:50 UTC by zulqarnainhanif

## Summary

Create menu for Inventory, Wallet and Trading like user menus

## Checklist
- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## References

https://github.com/XRFoundation/XREngine/issues/4430

## QA Steps

1. `git checkout pr_branch_name`
2. `npm install`
3. `npm run dev-reinit`
4. `npm run dev`

List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos.

## Reviewers

@HexaField @speigg @NateTheGreatt

2021-12-13 11:53 UTC, HexaField approved these changes

2021-12-13 11:54 UTC, HexaField requested changes
Just need to ensure the default routes point to the correct files in xrengine.config.ts

2021-12-13 14:35 UTC, swpnit82 commented
Please check this error after look like you missed some pages in "xrengine/client/src/pages/"


[plugin:vite:import-analysis] Failed to resolve import "@xrengine/client/src/pages/inventory" from "../projects/projects/default-project/xrengine.config.ts". Does the file exist?
/Users/User/XREngine/packages/projects/projects/default-project/xrengine.config.ts:33:31
31 |      },
32 |      "/inventory": {
33 |        component: () => import("@xrengine/client/src/pages/inventory")
   |                                ^
34 |      },
35 |      "/trading": {
    at formatError (/Users/User/XREngine/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42189:46)
    at TransformContext.error (/Users/User/XREngine/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42185:19)
    at normalizeUrl (/Users/User/XREngine/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:67284:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TransformContext.transform (/Users/User/XREngine/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:67424:57)
    at async Object.transform (/Users/User/XREngine/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42396:30)
    at async doTransform (/Users/User/XREngine/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:56801:29
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

2021-12-15 07:24 UTC, HexaField approved these changes

2021-12-15 07:24 UTC, merged