Hotfix: Add missing world tick in outgoing network state.
XRFoundation/XREngine pull request #4541
Opened 2021-12-22 09:10 UTC by hamzzam

## Summary
World fixed tick was removed from the outgoing network state due to which default tick of -1 is sent out each time and results in strange behaviours related to networking.

## Checklist
- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## References

References to pertaining issue(s)

## QA Steps

1. `git checkout pr_branch_name`
2. `npm install`
3. `npm run dev-reinit`
4. `npm run dev`

List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos.

## Reviewers

@HexaField @speigg @NateTheGreatt

2021-12-22 15:42 UTC, NateTheGreatt approved these changes

2021-12-22 17:46 UTC, NateTheGreatt requested changes
lets add a test for this to prevent regression bugs in the future

2021-12-23 03:33 UTC, HexaField approved these changes

2021-12-23 04:50 UTC, speigg approved these changes

2021-12-23 04:50 UTC, merged