Client core typescript
XRFoundation/XREngine pull request #4675
Opened 2022-01-06 06:24 UTC by Abhishek-Pathak-Here

## Summary

A summary of changes being made in this PR

## Checklist
- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## References

References to pertaining issue(s)

## QA Steps

1. `git checkout pr_branch_name`
2. `npm install`
3. `npm run dev-reinit`
4. `npm run dev`

List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos.

## Reviewers

@HexaField @speigg @NateTheGreatt

2022-01-07 06:46 UTC, barankyle requested changes

2022-01-07 06:46 UTC, barankyle commented on packages/client-core/src/admin/components/Location/LocationTable.tsx
> +      el.location_settings?.locationType,
All of these actually need to be 'location_setting', without the 's', unless something else got changed to make that work. Sequelize singularizes table names if it's only getting a single item. While the table name is 'location_settings', it's populated on the location when returned to the client as 'location_setting'.

2022-01-10 02:39 UTC, HexaField commented
Let's get this passing checks, tested and pulled in ASAP and continue on in smaller PRs.

2022-01-11 04:12 UTC, HexaField approved these changes

2022-01-11 04:12 UTC, merged