Fix show error
XRFoundation/XREngine pull request #4910
Opened 2022-01-24 16:41 UTC by FabriceIRANKUNDA

## Summary

A summary of changes being made in this PR

## Checklist
- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## References
#4858 

References to pertaining issue(s)

## QA Steps

1. `git checkout pr_branch_name`
2. `npm install`
3. `npm run dev-reinit`
4. `npm run dev`

List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos.

## Reviewers

@HexaField @speigg @NateTheGreatt

2022-01-25 02:55 UTC, NPatel10 commented on packages/editor/src/components/hierarchy/HierarchyTreeNode.tsx
> +  // const component = getComponent(node.entityNode.entity, AudioComponent)
remove line if not needed

2022-01-25 02:55 UTC, NPatel10 requested changes
Remove any commented code line if not needed any more

2022-01-25 22:49 UTC, HexaField commented
I wonder if we should have a separate tag component for errors, that way we dont have to duplicate showing the error for each component in the hierarchy

2022-01-26 20:14 UTC, HexaField approved these changes

2022-01-27 08:29 UTC, HexaField approved these changes

2022-01-28 03:21 UTC, NPatel10 approved these changes

2022-01-28 03:36 UTC, merged