All Editor Scenes Generate Cubemap
XRFoundation/XREngine pull request #5132
Opened 2022-02-09 10:18 UTC by FabriceIRANKUNDA

## Summary
while saving scene cubemap will be generated alongside a screenshot
Fixed error when scene preview button clicked without a scene loaded
_A summary of changes being made in this PR_

## Checklist
- [x] Pre-push checks pass `npm run check`
  - [x] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [x] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## References
#4869
_References to pertaining issue(s)_

## QA Steps

1. `git checkout pr_branch_name`
2. `npm install`
3. `npm run dev-reinit`
4. `npm run dev`

List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos.

## Reviewers

_Reviewers for this PR_
@HexaField

2022-02-09 12:49 UTC, NPatel10 approved these changes

2022-02-11 03:47 UTC, HexaField requested changes
when i try this, it is not rendering anything to the cubemap file, and the scene becomes invisible. i think we need to be using `uploadBakeToServer` instead of just `prepareSceneForBake` as there is more scene handling

2022-02-11 11:24 UTC, FabriceIRANKUNDA commented
> when i try this, it is not rendering anything to the cubemap file, and the scene becomes invisible. i think we need to be using `uploadBakeToServer` instead of just `prepareSceneForBake` as there is more scene handling

I think the problem was in the upload function where getToken was still used and uploading to the server was failing with a not authenticated error. I have removed getToken you may check again.

2022-02-16 09:35 UTC, NPatel10 approved these changes

2022-02-16 09:36 UTC, merged