Fix avatar old one behind issue
XRFoundation/XREngine pull request #5142
Opened 2022-02-09 20:50 UTC by rondoor124

## Summary

This is the PR for issue #5059

## Checklist
- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## References

_References to pertaining issue(s)_

## QA Steps

1. `git checkout pr_branch_name`
2. `npm install`
3. `npm run dev-reinit`
4. `npm run dev`

List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos.

## Reviewers

@HexaField, @mohsenheydari

2022-02-09 21:03 UTC, HexaField requested changes

2022-02-09 21:03 UTC, HexaField commented on packages/engine/src/avatar/functions/avatarFunctions.ts
> +      object3DComponent.value.userData.scale = 0.01
we can avoid the conditional here by doing `object3DComponent.value!.userData.scale = 0.01` since we know Object3DComponent.value will be defined

2022-02-09 21:03 UTC, HexaField commented on packages/engine/src/avatar/functions/avatarFunctions.ts
> +    if (!material.userData && !material.userData.shader) return
this can be shortened to `if (!material.userData?.shader)`

2022-02-09 21:03 UTC, HexaField commented on packages/engine/src/avatar/AvatarLoadingSystem.ts
> +            if (object.userData && object.userData.scale) {
this can be shortened to `if (object.userData?.scale)`

2022-02-09 21:10 UTC, rondoor124 commented on packages/engine/src/assets/classes/AssetLoader.ts
> +    onLoad(asset.scene ? asset : { scene: asset })
Thanks for the feedback. I will fix its soon.

2022-02-10 01:10 UTC, HexaField approved these changes

2022-02-10 01:11 UTC, merged