Improve static files cdn
XRFoundation/XREngine pull request #5309
Opened 2022-02-23 13:59 UTC by FabriceIRANKUNDA

## Summary
_A summary of changes being made in this PR_
Able:
to list all files and folders of the project in the admin system
Navigate through folders
Preview all files in both editor and admin system
Rename files
View properties of a file and folder (size, name, type and URL) in both editor and admin system

## Checklist
- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## References
#5263 
_References to pertaining issue(s)_

## QA Steps

1. `git checkout pr_branch_name`
2. `npm install`
3. `npm run dev-reinit`
4. `npm run dev`

List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos.

## Reviewers

_Reviewers for this PR_

2022-02-25 22:06 UTC, barankyle commented
The text file viewing is good. I'd like it to be better formatted, rather than be one big block of text without the empty lines that I know are in many of those files; formatted JSON, with indentation for each sub-level of values, would also be nice. Still don't see the name/filetype/size of selected files/folders.

2022-02-26 02:50 UTC, FabriceIRANKUNDA commented
> The text file viewing is good. I'd like it to be better formatted, rather than be one big block of text without the empty lines that I know are in many of those files; formatted JSON, with indentation for each sub-level of values, would also be nice. Still don't see the name/filetype/size of selected files/folders.

Good! To see the properties of a file/folder just do right click on a folder/file and choose properties and you can see that.

2022-03-03 21:46 UTC, barankyle requested changes
I would prefer for file names in the list to have the extension on them, e.g. 'xrengine.config.ts' instead of just 'xrengine.config'. To me, it's easier to know what they all are at a glance, rather than having to right click and then open the file properties to see the file type. I see the little icons to the left of the name that indicate model/image/text/etc., but I think seeing the extension would help, too.

I would also like to see a "[breadcrumbs](https://en.wikipedia.org/wiki/Breadcrumb_navigation)" directory hierarchy along the top of the file browser, so that you can see what folder you're currently in. Once you start diving down folders, you sometimes aren't sure where you are; seeing that you're in projects/project_1/assets/ would help, as would the ability to quickly jump back to the root of a project in a single click rather than having to click the back button several times.

2022-03-03 21:46 UTC, barankyle commented on packages/editor/src/components/assets/FileBrowserGrid.tsx
> +          <MenuItem onClick={viewAssetProperties}>{t('editor:layout.filebrowser.viewAssetProperties')}</MenuItem>
It looks like this needs an entry in i18n/en/editor.json.

2022-03-04 18:43 UTC, barankyle approved these changes

2022-03-05 02:02 UTC, HexaField commented
![Screenshot from 2022-03-05 13-01-57](https://user-images.githubusercontent.com/10372036/156863386-e320ea63-46dc-4275-b8af-9a3d4523705d.png)
folder properties do not display folder path in URL

2022-03-05 02:05 UTC, HexaField commented
When trying to delete a folder
```
[server] [server] [Error: EISDIR: illegal operation on a directory, unlink '/home/josh/Desktop/XREngine/packages/server/upload/projects/msa'] {
[server] [server]   errno: -21,
[server] [server]   code: 'EISDIR',
[server] [server]   syscall: 'unlink',
[server] [server]   path: '/home/josh/Desktop/XREngine/packages/server/upload/projects/msa'
[server] [server] }
```

2022-03-05 02:06 UTC, HexaField commented
![Screenshot from 2022-03-05 13-05-55](https://user-images.githubusercontent.com/10372036/156863509-1add11fd-e9bf-4d74-8060-bbc308929748.png)
model preview should take up whole area

2022-03-05 02:07 UTC, HexaField commented
![Screenshot from 2022-03-05 13-07-11](https://user-images.githubusercontent.com/10372036/156863555-ca9de5ed-6ee5-4512-85dc-ee6ef34b2f0c.png)
model preview should only have white lights (see discolouration)

2022-03-05 02:08 UTC, HexaField requested changes
left some review comments

2022-03-09 01:37 UTC, merged