Fixed fetching of current closest users and their media.
XRFoundation/XREngine pull request #5412
Opened 2022-03-04 21:06 UTC by barankyle

## Summary

MediaStreamService had been disabled on the client. Re-enabled it, and made pause/resume
producer/consumer functions push their actions to mediasoupOperationQueue.

Complete split of world and media servers had resulted in WebRTCRequestCurrentProducers message
being sent to world server, which has no knowledge of producers. Added a new MediaStreamSystem
message `TRIGGER_REQUEST_CURRENT_PRODUCERS`; the world server now gets the closest users and
sends them with that message, with the media server setup adding a listener to take that list
and call RequestCurrentProducers from the media server.

With new hookstate implementation, updated PartyVideoWindows to properly use nearbyLayerUsers
to populate PartyParticipantWindows.

## Checklist
- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## References

_References to pertaining issue(s)_

## QA Steps

1. `git checkout pr_branch_name`
2. `npm install`
3. `npm run dev-reinit`
4. `npm run dev`

List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos.

## Reviewers

_Reviewers for this PR_

2022-03-05 02:36 UTC, HexaField requested changes

2022-03-05 02:36 UTC, HexaField commented on packages/client-core/src/components/World/LocationLoadHelper.tsx
> +    systemModulePromise: import('@xrengine/engine/src/networking/systems/MediaStreamSystem')
we should add this back to initializeRealitmeSystems in initialiseEngine.ts along with the conditional argument

2022-03-06 18:51 UTC, speigg approved these changes

2022-03-08 00:00 UTC, HexaField approved these changes

2022-03-08 00:28 UTC, merged