Some Editor UI improvements and bug fixes
XRFoundation/XREngine pull request #5567
Opened 2022-03-26 06:47 UTC by NPatel10

## Summary

Worked on following issues
- [x] #5387 
- [ ] #5490 

Also added some UI tweeks to make Vector 3 and Vector 2 inputs more stylistic
![Screenshot 2022-03-26 121703](https://user-images.githubusercontent.com/22111011/160228304-f4baeb29-c6ff-4ef9-ac29-f18e1151ad5a.jpg)

## Checklist
- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## QA Steps

1. `git checkout pr_branch_name`
2. `npm install`
3. `npm run dev-reinit`
4. `npm run dev`

List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos.

## Reviewers

_Reviewers for this PR_
@HexaField @zulqarnainhanif

2022-03-26 09:50 UTC, HexaField approved these changes

2022-03-28 03:37 UTC, dinomut1 commented
![brave_vzUzWk5lMN](https://user-images.githubusercontent.com/94419856/160322234-8c3321fb-2461-4ebc-b55c-be469b0ecf80.gif)

Seeing an issue where selection becomes locked onto last field in properties tab.

2022-03-28 03:40 UTC, dinomut1 requested changes
![brave_vzUzWk5lMN](https://user-images.githubusercontent.com/94419856/160322548-1e44fe3d-1892-4bf9-b7a5-acc5e3091acc.gif)
Need to fix the selection locking in the element properties tab

2022-03-28 07:41 UTC, NPatel10 commented
> ![brave_vzUzWk5lMN](https://user-images.githubusercontent.com/94419856/160322548-1e44fe3d-1892-4bf9-b7a5-acc5e3091acc.gif) Need to fix the selection locking in the element properties tab

Selection is fixed in latest push

2022-03-29 09:25 UTC, zulqarnainhanif approved these changes

2022-03-29 23:26 UTC, dinomut1 approved these changes

2022-03-29 23:27 UTC, merged