hot fix function in serialize transform.
XRFoundation/XREngine pull request #5587
Opened 2022-03-30 17:10 UTC by hamzzam

## Summary

_A summary of changes being made in this PR_

## Checklist
- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## References

_References to pertaining issue(s)_

## QA Steps

1. `git checkout pr_branch_name`
2. `npm install`
3. `npm run dev-reinit`
4. `npm run dev`

List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos.

## Reviewers

_Reviewers for this PR_

2022-03-30 23:14 UTC, HexaField approved these changes

2022-03-30 23:43 UTC, HexaField requested changes
gave this a test locally, it seem that this is not correct, the tests are failing displaying incorrect information with this change

2022-03-31 05:32 UTC, hamzzam commented
> gave this a test locally, it seem that this is not correct, the tests are failing displaying incorrect data with this change

Hey yeah I was having some errors when trying to duplicate and stuff on editor. Gave it a look again and turns out the errors were because of three js version.
Really sorry for this I will delete this PR.

2022-03-31 05:32 UTC, closed without merging

2022-03-31 06:36 UTC, HexaField commented
No prob!