File browser refactor and refinements
XRFoundation/XREngine pull request #5595
Opened 2022-03-31 05:12 UTC by NPatel10

## Summary

Added support to apply changes to `package/projects` for all the `file-browser` apis

## Checklist
- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## References
- [x] #5387 

## QA Steps

1. `git checkout pr_branch_name`
2. `npm install`
3. `npm run dev-reinit`
4. `npm run dev`

List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos.

## Reviewers
@HexaField @zulqarnainhanif

2022-03-31 17:08 UTC, zulqarnainhanif commented
getting below error in terminal on deleting through localhost

<img width="781" alt="Screenshot 2022-03-31 at 10 07 12 PM" src="https://user-images.githubusercontent.com/30355034/161111276-9219789f-8ac3-4710-bfe3-c3145a4ac0a7.png">

2022-04-01 02:26 UTC, HexaField requested changes

2022-04-05 00:48 UTC, HexaField requested changes

2022-04-05 00:48 UTC, HexaField commented on packages/editor/src/components/assets/FileBrowserContentPanel.tsx
> +      ? selectedDirectory.split('/')[-1] == dropOn.name
what is [-1] doing here?

2022-04-05 00:48 UTC, HexaField commented on packages/server-core/src/media/file-browser/file-browser.test.ts
> +  it('patche file with new data', async () => {
typo: `patche` should be `patch`

2022-04-05 12:47 UTC, NPatel10 commented on packages/editor/src/components/assets/FileBrowserContentPanel.tsx
> +      ? selectedDirectory.split('/')[-1] == dropOn.name
Simplified the logic

2022-04-07 03:21 UTC, HexaField requested changes
Uploading a file to the root of a project seems to add it as both a file and a folder.

Trying to drag any asset from the file browser to a text properties field copies incorrectly by appending `undefined` at the end of the path for example: `/image.pngundefined`

2022-04-08 05:39 UTC, NPatel10 commented
@HexaField, Not able to reproduce below one, can you provide more steps?

> Uploading a file to the root of a project seems to add it as both a file and a folder.

2022-04-09 02:16 UTC, HexaField commented
> @HexaField, Not able to reproduce below one, can you provide more steps?
> 
> > Uploading a file to the root of a project seems to add it as both a file and a folder.

1. drag a file into the file browser panel
2. once it finishes uploading, it shows as both a folder and a file with the same name

![Screenshot from 2022-04-09 12-14-32](https://user-images.githubusercontent.com/10372036/162552803-cd3cecd8-655d-4ba5-8142-18f2c16c25ce.png)

2022-04-11 04:24 UTC, NPatel10 commented
> Uploading a file to the root of a project seems to add it as both a file and a folder.

Can we create a separate issue for this bug, Because I am not able to regenerate it in my system. Maybe an OS issue?

![Screenshot 2022-03-26 121703](https://user-images.githubusercontent.com/22111011/162664731-ecf96a95-52a1-4b28-98db-f1c63df65ad4.jpg)

2022-04-11 09:25 UTC, HexaField approved these changes

2022-04-11 09:40 UTC, merged