HyperFlux WIP
XRFoundation/XREngine pull request #5604
Opened 2022-03-31 22:58 UTC by speigg

## Summary

HyperFlux — brings together various state management in XREngine, in a way that makes it easy to introspect and test. 

## Checklist
- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## References

_References to pertaining issue(s)_

## QA Steps

1. `git checkout pr_branch_name`
2. `npm install`
3. `npm run dev-reinit`
4. `npm run dev`

List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos.

## Reviewers

_Reviewers for this PR_

2022-04-08 07:04 UTC, HexaField approved these changes

2022-04-08 07:27 UTC, HexaField requested changes
It seems like there is a bug where the users take a long time to join the world. The join world function in NetworkFunctions seems to be dispatching far into the future, so i am imagining there is an incorrect time calculation being done in the action dispatching. It is also peculiar that the time property in engine actions is showing as a float below 1, whereas the network actions are dispatching as an integer which looks like it corresponds to world tick. perhaps there is a mistake somewhere here.

Let's also get this fully tested before we merge it in to ensure we have no regressions.

2022-04-08 15:53 UTC, speigg commented
> It seems like there is a bug where the users take a long time to join the world. The join world function in NetworkFunctions seems to be dispatching far into the future, so i am imagining there is an incorrect time calculation being done in the action dispatching. It is also peculiar that the time property in engine actions is showing as a float below 1, whereas the network actions are dispatching as an integer which looks like it corresponds to world tick. perhaps there is a mistake somewhere here.
> 
> Let's also get this fully tested before we merge it in to ensure we have no regressions.



> It seems like there is a bug where the users take a long time to join the world. The join world function in NetworkFunctions seems to be dispatching far into the future, so i am imagining there is an incorrect time calculation being done in the action dispatching.

That's correct; I thought I pushed the fix last night before I went to sleep haha. 

> Let's also get this fully tested before we merge it in to ensure we have no regressions. 

Writing tests today

2022-04-14 23:30 UTC, HexaField approved these changes

2022-04-15 00:48 UTC, merged