Minor readme/markdown formatting fixes.
XRFoundation/XREngine pull request #5611
Opened 2022-04-01 23:10 UTC by dmitrizagidulin

Minor whitespace/formatting tweaks of README and installation markdown.
(Remove extra trailing spaces, enforce line breaks, minor other fixes.)

2022-04-02 01:03 UTC, speigg requested changes

2022-04-02 01:03 UTC, speigg commented on README.md
> +Web AR, VR. XR should be easy.
Extra period here after VR

2022-04-02 01:07 UTC, dmitrizagidulin commented on README.md
> +Web AR, VR. XR should be easy.
@speigg thanks, fixed.

2022-04-03 00:50 UTC, speigg approved these changes

2022-04-03 01:32 UTC, merged