Add "Import Asset" Button to Editor Menu Bar
XRFoundation/XREngine pull request #5655
Opened 2022-04-05 20:38 UTC by dinomut1

## Summary

Adds a quick way to upload files into the editor. Beginnings of Asset wrapper class. 
Automatically extracts zip files into directory with same name.
This can be used to quickly upload glTF files with resources.
## Checklist
- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## References

https://github.com/XRFoundation/XREngine/issues/5518

## QA Steps

1. `git checkout pr_branch_name`
2. `npm install`
3. `npm run dev-reinit`
4. `npm run dev`
5. in editor, open the menu bar and use the new "Import Asset" button to import any compatible files into the project assets folder.
List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos.

## Reviewers

_Reviewers for this PR_

2022-04-06 02:37 UTC, NPatel10 approved these changes

2022-04-06 03:28 UTC, HexaField requested changes

2022-04-06 03:28 UTC, HexaField commented on packages/editor/src/components/EditorContainer.tsx
> +  const importAsset = async (fileName: string, asset: any) => {}
is this still needed?

2022-04-06 03:28 UTC, HexaField commented on package.json
> +    "extract-zip": "^2.0.1",
if this is only used in server core it should be moved to the server core deps

2022-04-06 03:28 UTC, HexaField commented on packages/editor/src/components/EditorContainer.tsx
> +    const el = document.createElement('input')
make sure we are cleaning up this element in case it is not automatically garbage collected

2022-04-06 03:28 UTC, HexaField commented on packages/engine/src/assets/classes/Asset.ts
> +export class Asset {
do we need to declare these as classes? Can we use a functional approach instead?

2022-04-06 03:28 UTC, HexaField commented on packages/engine/src/scene/functions/SceneLoading.ts
> +export const loadSceneFromJSON = async (sceneData: SceneJson, world = useWorld(), additive = false) => {
are we using additive anywhere? What is the purpose here?

2022-04-06 03:29 UTC, HexaField requested changes

2022-04-06 03:29 UTC, HexaField commented on packages/server-core/src/assets/assetLibrary/assetLibrary.class.ts
> +  async get(id: Id, params?: Params) {
if this is unused, lets reduce it to a noop

2022-04-06 17:18 UTC, dinomut1 commented on packages/editor/src/components/EditorContainer.tsx
> +  const importAsset = async (fileName: string, asset: any) => {}
nay

2022-04-18 23:35 UTC, HexaField requested changes

2022-04-18 23:35 UTC, HexaField commented on packages/editor/src/functions/assetFunctions.ts
> +  const ass = getComponent(node.entity, AssetComponent)
lets use more descriptive full variable names here. `assetComponent` instead of `ass`

2022-04-18 23:35 UTC, HexaField commented on packages/engine/src/scene/systems/AssetSystem.ts
>        const ass = getComponent(entity, AssetComponent)
more descriptve name

2022-04-19 03:47 UTC, merged