Replace winston and console with pino logger.
XRFoundation/XREngine pull request #5813
Opened 2022-04-21 03:57 UTC by dmitrizagidulin

## Summary

- Replaces Winston logger with `pino`
- Replaces usages of `console.log` with appropriate logger statements.
- Removes usage of deprecated `feathers-logger` package 
- Also enhances `dev-agones-silent` npm script by using the cross-platform `dev-null-cli`  package

## References

Partly addresses issue #2799.

## Checklist
- [x] CI/CD checks pass `npm run check`

2022-04-21 06:18 UTC, HexaField approved these changes

2022-04-21 12:18 UTC, speigg requested changes

2022-04-21 14:02 UTC, dmitrizagidulin commented on packages/server-core/src/media/upload-media/upload-asset.service.ts
> +        logger.info('upload-asset' + { data, files })
@speigg ::facepalms:: good catch, thanks. will fix

2022-04-21 19:33 UTC, dmitrizagidulin commented on packages/server-core/src/media/upload-media/upload-asset.service.ts
> +        logger.info('upload-asset' + { data, files })
@speigg fixed.

2022-04-21 22:39 UTC, speigg commented
@dmitrizagidulin I think you have to supply printf-style placeholders in pino to serialize additional parameters. See https://github.com/pinojs/pino/blob/master/docs/api.md#interpolationvalues-any

2022-04-23 22:29 UTC, dmitrizagidulin commented
@speigg - ok, changed my mind on adding the custom hook; refactored all the logger usage to fit the function signature.
(Apologies for the oversight, I was in a hurry)

2022-04-23 22:37 UTC, speigg approved these changes

2022-04-23 22:39 UTC, speigg commented
@dmitrizagidulin looks good, thank! Just waiting for CI/CD to finish and then I'll merge to dev!

2022-04-23 22:42 UTC, speigg commented
@dmitrizagidulin looks like we have a few typescript errors:

Error: @xrengine/analytics: ../server-core/src/hooks/party-user-permission-authenticate.ts(25,16): error TS2339: Property 'err' does not exist on type 'Logger<{ transport: { target: string; options: { colorize: boolean; translateTime: boolean; }; }; }>'.
Error: @xrengine/analytics: ../server-core/src/updateAppConfig.ts(348,75): error TS2552: Cannot find name 'message'. Did you mean 'onmessage'?


You can run `npm run check-errors` to reproduce locally. Can you fix these before we merge?

2022-04-24 00:48 UTC, merged