Configurable Camera Raycast + Avatar Upload Fix
XRFoundation/XREngine pull request #5881
Opened 2022-04-28 01:39 UTC by dinomut1

## Summary

Camera raycasting is one of the most expensive systems in the engine. This PR adds config settings for the camera raycasting that can be accessed in a scene's root node in editor. Camera raycasting is set to be disabled by default.

Also fixes an error with avatar uploading by checking for AvatarAnimation and Velocity components before performing bone retargeting.

## Checklist
- [ ] CI/CD checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Typescript passing via `npm run check-errors`
  - [ ] Unit & Integration tests passing via `npm run test`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## Reviewers

_Reviewers for this PR_

2022-04-28 09:16 UTC, HexaField requested changes
i fixed up a few convention inconsistencies, and fixed the LoopAnimationComponent error in a previous PR, so i reverted the change to avatarFunctions.ts

although i am a bit confused, why are creating a new `camera` serializer/deserializer rather than extending `camera-properties` ?

also, why is this new camera in the camera folder rather than with all the other scene loader functions in /scene/functions/loaders?

lets try and unify these to the existing `camera-properties`

when this is done, lets also ensure not just the default project but all the scenes have this change

we also need to be adding tests for these sorts of changes, to prove functionality (i have a few concerns about how it currently is handled either way, which should be fixed by adhering to the existing `camera-properties`) as well as to stop regressions

2022-04-28 11:58 UTC, speigg commented
I dug into this, and what's actually slowing things down seems to not be the recasting itself, but the fact that we have hundreds of collider objects in some scenes. I think we need to address the root cause here. First of all, it's redundant to be checking both scene geometry _and_ scene colliders. Second, all these colliders are also slowing down the rendering system, since they are being iterated there every frame as well.

2022-04-29 03:43 UTC, dinomut1 commented
Merged in the camera raycasting data into the camera properties component, so that was straightforward. However I am getting the null ref regarding the AvatarAnimationComponent when doing avatar upload. If that is tied into other changes being done I won't touch it.

2022-05-07 00:27 UTC, HexaField requested changes

2022-05-07 00:27 UTC, HexaField commented on packages/engine/src/scene/functions/GLTFConversion.ts
> +  if (Engine.instance.publicPath == undefined) return
the public path should always be defined (needs to be manually defined in tests that rely on it) rather than aborting

2022-05-07 00:54 UTC, dinomut1 commented on packages/engine/src/scene/systems/SceneObjectSystem.ts
> +      if (!hasComponent(entity, Object3DComponent)) return
An Object3DComponent can be added and then removed in one world execution frame, which then causes the entry query to contain entities that do not have the components in the query.

2022-05-07 02:00 UTC, merged