hide new massage dot and added alert sound on new message
XRFoundation/XREngine pull request #6025
Opened 2022-05-10 09:45 UTC by FabriceIRANKUNDA

## Summary

_A summary of changes being made in this PR_

## References
#6004 
closes #_insert number here_

## Checklist
- [ ] CI/CD checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Typescript passing via `npm run check-errors`
  - [ ] Unit & Integration tests passing via `npm run test`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

## Reviewers

_Reviewers for this PR_

2022-05-10 09:56 UTC, HexaField requested changes

2022-05-10 09:56 UTC, HexaField commented on packages/client-core/src/components/InstanceChat/index.tsx
> +      const audio = new Audio(notificationAlertURL)
we should see if we need to manually clean this up or if it will be handled with the garbage collector, or better yet if we can re-use the audio node

2022-05-10 09:56 UTC, HexaField commented on packages/common/src/constants/URL.ts
> +export const notificationAlertURL = 'http://codeskulptor-demos.commondatastorage.googleapis.com/pang/pop.mp3'
we should download this file and server it from /packages/client/public folder

2022-05-10 21:11 UTC, HexaField approved these changes

2022-05-12 02:42 UTC, HexaField requested changes
- notification plays when loading messages before a user has joined
- audio settings slider should influence the volume of the alert

we may want to handle this audio via the engine, so we have greater control over it, and spatialize it when we implement it in ethereal

2022-05-12 23:17 UTC, HexaField requested changes
this is on the right path, but we need to separate these audio settings out of the render settings. instead of engine/src/renderer/EngineRendererState we need these new variables to be in engine/src/audio/AudioState

2022-05-18 02:11 UTC, closed without merging

2022-05-18 02:30 UTC, dmitrizagidulin commented
PR Moved to https://github.com/XRFoundation/XREngine/pull/6114