IK - Upper Arm Twist Fix
XRFoundation/XREngine pull request #6319
Opened 2022-06-03 10:49 UTC by mohsenheydari

Adds common 3D axis definitions

## Summary

* Fixes the upper arm twisting issue
* Adds common 3D axis definitions

## References

closes #_insert number here_

## Checklist
- [ ] CI/CD checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Typescript passing via `npm run check-errors`
  - [ ] Unit & Integration tests passing via `npm run test`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

## Reviewers

_Reviewers for this PR_

2022-06-03 12:55 UTC, speigg requested changes

2022-06-03 12:55 UTC, speigg commented on packages/engine/src/common/constants/Axis3D.ts
> +export const X = {
We should be using standard types to ensure that functions remain highly optimized by the javascript JIT. 

This is what I've done for constants in the past:


```ts

export const V_00 = Object.freeze(new Vector2(0,0))
export const V_11 = Object.freeze(new Vector2(1,1))
export const V_000 = Object.freeze(new Vector3(0,0,0))
export const V_100 = Object.freeze(new Vector3(1,0,0))
export const V_010 = Object.freeze(new Vector3(0,1,0))
export const V_001 = Object.freeze(new Vector3(0,0,1))
export const V_111 = Object.freeze(new Vector3(1,1,1))
export const Q_IDENTITY = Object.freeze(new Quaternion)

export const DIRECTION = {
    RIGHT: Object.freeze(new Vector3(1, 0, 0)),
    UP: Object.freeze(new Vector3(0, 1, 0)),
    NEAR: Object.freeze(new Vector3(0, 0, 1)),
    LEFT: Object.freeze(new Vector3(-1, 0, 0)),
    DOWN: Object.freeze(new Vector3(0, -1, 0)),
    FAR: Object.freeze(new Vector3(0, 0, -1))
}
```

2022-06-04 05:18 UTC, HexaField requested changes

2022-06-04 05:18 UTC, HexaField commented on packages/engine/src/common/constants/Axis3D.ts
> +export const X = Object.freeze(new Vector3(1, 0, 0))
let's rename these to `xAxis`, `rightDirection` etc to be a little more descriptive

2022-06-06 23:19 UTC, HexaField approved these changes

2022-06-06 23:19 UTC, merged