Video textures
XRFoundation/XREngine pull request #6503
Opened 2022-06-27 18:12 UTC by dinomut1

Adds video handling into AssetLoader. 
Adds video drag-and-drop capability to all texture fields of shaders in material library. 
Adds two fire materials to material library.

2022-06-28 00:18 UTC, speigg requested changes
Could you find a way to call video.play() on user input events (touchdown and click) so that this works on Safari?

2022-06-28 22:50 UTC, dinomut1 commented
TO TEST:
1. Open any scene in editor
2. Place a model into scene and load any .glb into it (I am using [matcube.zip](https://github.com/XRFoundation/XREngine/files/9005753/matcube.zip))
3. Click the + button in the model properties panel to add a material override.
![brave_ykQCoYp5jE](https://user-images.githubusercontent.com/94419856/176314654-62cb7cd6-5f33-40fa-aa02-3491b137c419.png)
4. Set the Material field to Basic
5. Open the 'Arguments' section and scroll to the 'map' property. 
![brave_5dQFLqRAYS](https://user-images.githubusercontent.com/94419856/176314955-d8f5e067-be65-484a-8161-3491c926b93e.png)
6. Use the 'Import Asset' button in the top left dropdown to import any .mp4 file into the project. The video file will be imported into the current project's 'assets' folder.
![brave_GCWFgUeKlI](https://user-images.githubusercontent.com/94419856/176315844-75dc30a7-23de-481b-ba8f-79ff13578bd4.png)
![brave_hARob7q7dA](https://user-images.githubusercontent.com/94419856/176315852-1899be91-643d-4707-84b3-1f4bc6614e71.png)
7. Drag the video file from the file browser into the 'map' field of the material override.
![brave_jifKTGbvOJ](https://user-images.githubusercontent.com/94419856/176316255-46fb0659-5f53-4d3a-8a75-c961d4e4fb89.png)
8. Change the 'Pattern' field of the override to be blank. Then press refresh button at the top of the override list.
9. The override is now waiting on user input to play the video texture. Click anywhere in the scene to trigger it.
https://user-images.githubusercontent.com/94419856/176317096-a858dfd6-e836-47ba-a609-b27c97a2ac6f.mp4

2022-06-29 06:28 UTC, NPatel10 approved these changes

2022-06-30 18:32 UTC, speigg approved these changes

2022-06-30 18:32 UTC, merged