Updates for various dependencies
XRFoundation/XREngine pull request #6931
Opened 2022-09-13 07:01 UTC by hanzlamateen

## Summary

_A summary of changes being made in this PR_

## References

closes #_insert number here_

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] [ensure all checks pass](https://github.com/XRFoundation/XREngine/wiki/Testing-&-Contributing)
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

2022-09-16 18:07 UTC, barankyle approved these changes

2022-09-16 18:25 UTC, barankyle requested changes
It looks like the new version of feathers is more strictly defining Params, and so check-errors is throwing a lot of errors now. We probably need to make custom Params interfaces for all of these occurrences that specify the parameters that each erroring function is going to use.

2022-09-16 22:04 UTC, HexaField commented
> It looks like the new version of feathers is more strictly defining Params, and so check-errors is throwing a lot of errors now. We probably need to make custom Params interfaces for all of these occurrences that specify the parameters that each erroring function is going to use.

Agreed, the more we can strictly type everything the better.

2022-09-21 16:52 UTC, barankyle approved these changes

2022-09-22 00:30 UTC, merged