MAPPA - Animation tools
XRFoundation/XREngine pull request #6996
Opened 2022-09-22 21:54 UTC by patreeceeo

## Summary

_A summary of changes being made in this PR_

## References

closes #_insert number here_

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] [ensure all checks pass](https://github.com/XRFoundation/XREngine/wiki/Testing-&-Contributing)
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

2022-09-22 22:42 UTC, HexaField commented
The first problem I see here is replacing the default avatars. This should be done via removing the default project, and creating your own, rather than overriding the base engine.

More generally, it would be better to see application specific features (UI, game logic, custom assets) implemented via a project rather than the base engine.

Project API can be found here https://github.com/XRFoundation/ethereal-engine-docs/blob/master/docs/3_concepts/1_projects_api.md

2022-09-22 22:48 UTC, HexaField requested changes

2022-09-22 22:48 UTC, HexaField commented on packages/engine/src/scene/systems/TriggerSystem.ts
>  import { Entity } from '../../ecs/classes/Entity'
the changes to this system must be reverted if this branch is to be merged, the existing functionality of triggers should cover all use cases. Please re-think the implementation here.

2022-09-22 22:48 UTC, HexaField commented on packages/engine/src/scene/functions/loaders/ModelFunctions.ts
> +function setupAnimations(model, scene, entity) {
what is the reason for doing this? this should be done in the existing LoopAnimationFunctions implementation

2022-09-27 00:00 UTC, closed without merging

2022-09-27 00:09 UTC, patreeceeo commented
Sorry, didn't mean to close this. Will reopen.

2022-09-27 00:09 UTC, patreeceeo commented
@AidanCaruso take a look at Josh's comments when you have a second.