KTX2 Support
XRFoundation/XREngine pull request #7490
Opened 2023-01-24 03:31 UTC by dinomut1

Support KTX2 compression in Model export.
Add "Compress" option in file browser, attached to KTX2Encode feathers service

2023-01-24 05:15 UTC, HexaField requested changes

2023-01-24 05:15 UTC, HexaField commented on packages/server-core/src/assets/ktx2-encode/ktx2-encode.service.ts
> +      create: any
we should add the return type for this API

2023-01-24 21:11 UTC, HexaField approved these changes

2023-01-25 00:30 UTC, speigg approved these changes

2023-01-25 00:30 UTC, merged