Migration/tailwind phase 2
XRFoundation/XREngine pull request #7583
Opened 2023-02-14 19:29 UTC by jerknose

## Summary

_A summary of changes being made in this PR_

## References

closes #_insert number here_

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] [ensure all checks pass](https://github.com/XRFoundation/XREngine/wiki/Testing-&-Contributing)
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

2023-02-21 23:08 UTC, barankyle requested changes
Seeing some bugs that hopefully only require minor fixes:

~~* startIcons on Buttons are not rendering properly for me. They all show up as X's. This can be seen on the login page - screenshot attached
![MUIstartIconBug](https://user-images.githubusercontent.com/8977377/220476660-19fbdc95-ba6f-4120-91ff-b6a7e54443a6.png)~~

~~* The admin pages aren't functional, in that I can't click on content within the page. The navigation on the left side works, but nothing specific to each admin page is clickable. Maybe this is a z-index issue?~~

* There's a purplish border on some button on the admin pages. Here's a screenshot from /admin/projects; the three big buttons at the top and the Refresh Github Repo Access button have this border:
![AdminProjectPageBorderBug](https://user-images.githubusercontent.com/8977377/220501712-2270af01-0946-4d59-b312-52a7797e5446.png)


~~* /admin/projects is throwing the following warning:
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ForwardRef(Tooltip2)`.
    at Icon (https://localhost:3000/@fs/home/kyle/Development/Forks/xrengine/packages/ui/src/Icon/index.tsx:130:17)
    at Tooltip2 (https://localhost:3000/node_modules/.vite/deps/@mui_material.js?v=09e9b42f:25885:17)
    at Tooltip
    at div
    at O2 (https://localhost:3000/node_modules/.vite/deps/chunk-SGXG4WFK.js?v=09e9b42f:1066:6)
    at Box3 (https://localhost:3000/node_modules/.vite/deps/chunk-GF2L3GBV.js?v=09e9b42f:2052:19)
    at Box (https://localhost:3000/@fs/home/kyle/Development/Forks/xrengine/packages/ui/src/Box/index.tsx:3:16)
    at td
    at O2 (https://localhost:3000/node_modules/.vite/deps/chunk-SGXG4WFK.js?v=09e9b42f:1066:6)
    at TableCell2 (https://localhost:3000/node_modules/.vite/deps/@mui_material.js?v=09e9b42f:29670:17)
    at TableCell (https://localhost:3000/@fs/home/kyle/Development/Forks/xrengine/packages/ui/src/TableCell/index.tsx:3:22)
<snipped for some semblance of conciseness>
```~~

* /admin/routes is throwing this:
```
Warning: Styled(input) contains an input of type checkbox with both checked and defaultChecked props. Input elements must be either controlled or uncontrolled (specify either the checked prop, or the defaultChecked prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://reactjs.org/link/controlled-components
    at input
    at O2 (https://localhost:3000/node_modules/.vite/deps/chunk-SGXG4WFK.js?v=09e9b42f:1066:6)
    at span
    at O2 (https://localhost:3000/node_modules/.vite/deps/chunk-SGXG4WFK.js?v=09e9b42f:1066:6)
    at ButtonBase2 (https://localhost:3000/node_modules/.vite/deps/chunk-LNA6ROTB.js?v=09e9b42f:10261:17)
    at O2 (https://localhost:3000/node_modules/.vite/deps/chunk-SGXG4WFK.js?v=09e9b42f:1066:6)
    at SwitchBase2 (https://localhost:3000/node_modules/.vite/deps/@mui_material.js?v=09e9b42f:9195:5)
    at O2 (https://localhost:3000/node_modules/.vite/deps/chunk-SGXG4WFK.js?v=09e9b42f:1066:6)
    at Checkbox2 (https://localhost:3000/node_modules/.vite/deps/@mui_material.js?v=09e9b42f:9483:17)
    at Checkbox
    at td
    at O2 (https://localhost:3000/node_modules/.vite/deps/chunk-SGXG4WFK.js?v=09e9b42f:1066:6)
    at TableCell2 (https://localhost:3000/node_modules/.vite/deps/@mui_material.js?v=09e9b42f:29670:17)
    at TableCell (https://localhost:3000/@fs/home/kyle/Development/Forks/xrengine/packages/ui/src/TableCell/index.tsx:3:22)
<snip>
```

~~* /admin/users is throwing:
```
react-dom.development.js:86 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ForwardRef(Tooltip2)`.
    at Icon (https://localhost:3000/@fs/home/kyle/Development/Forks/xrengine/packages/ui/src/Icon/index.tsx:130:17)
    at Tooltip2 (https://localhost:3000/node_modules/.vite/deps/@mui_material.js?v=09e9b42f:25885:17)
    at Tooltip
    at div
    at O2 (https://localhost:3000/node_modules/.vite/deps/chunk-SGXG4WFK.js?v=09e9b42f:1066:6)
    at Box3 (https://localhost:3000/node_modules/.vite/deps/chunk-GF2L3GBV.js?v=09e9b42f:2052:19)
    at Box (https://localhost:3000/@fs/home/kyle/Development/Forks/xrengine/packages/ui/src/Box/index.tsx:3:16)
    at td
    at O2 (https://localhost:3000/node_modules/.vite/deps/chunk-SGXG4WFK.js?v=09e9b42f:1066:6)
    at TableCell2 (https://localhost:3000/node_modules/.vite/deps/@mui_material.js?v=09e9b42f:29670:17)
    at TableCell (https://localhost:3000/@fs/home/kyle/Development/Forks/xrengine/packages/ui/src/TableCell/index.tsx:3:22)
<snip>
```~~

* /admin/avatars is throwing the same error about checkboxes, and also:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'state')
    at getRendererSceneMetadataState (WebGLRendererSystem.ts:323:59)
    at ShadowSystem.ts:107:37
    at renderWithHooks (react-reconciler.development.js:7478:18)
    at mountIndeterminateComponent (react-reconciler.development.js:11247:13)
<snip>
```

* /admin/bots is throwing this:
```
react.development.js:209 Warning: Failed prop type: Invalid prop `className` of type `object` supplied to `ForwardRef(Dialog2)`, expected `string`.
    at Dialog2 (https://localhost:3000/node_modules/.vite/deps/@mui_material.js?v=09e9b42f:10511:17)
    at Dialog (https://localhost:3000/@fs/home/kyle/Development/Forks/xrengine/packages/ui/src/Dialog/index.tsx:6:19)
    at div
    at UpdateBot (https://localhost:3000/@fs/home/kyle/Development/Forks/xrengine/packages/client-core/src/admin/components/Bots/UpdateBot.tsx:19:22)
    at div
    at DisplayBots (https://localhost:3000/@fs/home/kyle/Development/Forks/xrengine/packages/client-core/src/admin/components/Bots/DisplayBots.tsx:19:35)
<snip>
```

* On /admin/locations, when I click on the 'View' button for a location, or click on the Create Location button, I get this:
```
Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at index.tsx:79:30
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24931:11)
```

index.tsx is in the stack trace is `client-core/src/common/components/InputText/index.tsx`

* /admin/users is now throwing
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ForwardRef(Tooltip2)`.
    at Icon (https://localhost:3000/@fs/home/kyle/Development/Forks/xrengine/packages/ui/src/Icon/index.tsx:135:17)
    at Tooltip2 (https://localhost:3000/node_modules/.vite/deps/@mui_material.js?v=4635a9a8:25885:17)
    at Tooltip
    at div
    at O2 (https://localhost:3000/node_modules/.vite/deps/chunk-SGXG4WFK.js?v=c28205d6:1066:6)
    at Box3 (https://localhost:3000/node_modules/.vite/deps/chunk-GF2L3GBV.js?v=c28205d6:2052:19)
    at Box (https://localhost:3000/@fs/home/kyle/Development/Forks/xrengine/packages/ui/src/Box/index.tsx:3:16)
```

* On /admin/settings, the icons next to each setting type is the EE Chevron instead of an individualized icon.

What I see:
![SettingsSelectorError](https://user-images.githubusercontent.com/8977377/220502358-47b5dec0-430f-4e90-abbd-1b171c8fdabe.png)
What it should look like:
![SettingsSelectorCorrect](https://user-images.githubusercontent.com/8977377/220502395-45a1b089-a3ca-499e-b983-375fc11664ce.png)

2023-02-22 01:52 UTC, jerknose commented
Icons should be fixed. @barankyle there are several of these types of errors that need to be fixed. But are unrelated to this PR. Can you check dev and create issues for these?

2023-02-22 09:56 UTC, hanzlamateen requested changes

2023-02-22 09:56 UTC, hanzlamateen commented on packages/ui/src/Card/Card.test.tsx
> +describe('Box', () => {
Here the import & test name should be `Card`

2023-02-22 09:56 UTC, hanzlamateen commented on packages/ui/src/Collapse/Collapse.test.tsx
> +describe('Container', () => {
This text name and Import should be `Collapse`

2023-02-22 09:56 UTC, hanzlamateen commented on packages/ui/src/Grid/index.stories.tsx
> +  title: 'MUI/List',
I think the Import and all references in this file should be `Grid` instead of `List`

2023-02-22 09:56 UTC, hanzlamateen commented on packages/ui/src/IconButton/index.tsx
> +      // onPointerUp={handleSoundEffect}
Any reason why the sound effects is disabled?

2023-02-22 09:56 UTC, hanzlamateen commented on packages/ui/src/SvgIcon/SvgIcon.test.tsx
> +describe('SVgIcon', () => {
Small Typo the import and test name should be `SvgIcon`. Watch out for V is currently upper caps.

2023-02-22 09:56 UTC, hanzlamateen commented on packages/client-core/src/admin/adminRoutes.tsx
> +import { SceneClientModule } from '@xrengine/engine/src/scene/SceneClientModule'
Some of these imports are not used in this file.

2023-02-22 10:10 UTC, hanzlamateen commented
On running `npm run predeploy` I am getting some errors and failed tests. Is this normal?

Also how to run storybook on my end. I tried running `npm run storybook` from `packages/ui` folder after running above command and getting error.

```
Snapshot Summary
 › 69 snapshots written from 69 test suites.

Test Suites: 2 failed, 69 passed, 71 total
Tests:       69 passed, 69 total
Snapshots:   69 written, 69 total
Time:        294.283 s
Ran all test suites.
Test results written to: tests/jest-test-results.json

> @xrengine/ui@0.0.1 build:storybook
> build-storybook -c .storybook -o build/

info @storybook/react v6.5.16
info
info => Cleaning outputDir: /home/hanzlamateen/xrengine/packages/ui/build/
info => Loading presets
info => Compiling manager..
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/home/hanzlamateen/xrengine/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/hanzlamateen/xrengine/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/hanzlamateen/xrengine/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/hanzlamateen/xrengine/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/hanzlamateen/xrengine/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/hanzlamateen/xrengine/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/hanzlamateen/xrengine/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/hanzlamateen/xrengine/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/hanzlamateen/xrengine/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/hanzlamateen/xrengine/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/hanzlamateen/xrengine/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.6.0
npm ERR! Lifecycle script `build:storybook` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @xrengine/ui@0.0.1
npm ERR!   at location: /home/hanzlamateen/xrengine/packages/ui
npm ERR! Lifecycle script `predeploy` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @xrengine/ui@0.0.1
npm ERR!   at location: /home/hanzlamateen/xrengine/packages/ui
```

2023-02-22 10:26 UTC, hanzlamateen commented
> 

I also faced these issues, specially the purple border arround buttons and icon on `/admin/settings` being wrong.

2023-02-22 10:29 UTC, hanzlamateen commented
Some social icons on ProfileMenu are appearing in small size.

![image](https://user-images.githubusercontent.com/10975502/220593881-3acf485f-408d-46b3-8798-b1c5ae436c6e.png)

2023-02-22 10:40 UTC, hanzlamateen commented
The icons of `EmoteMenu` seems to be messed up 😬
![image](https://user-images.githubusercontent.com/10975502/220596124-c0fd0576-3a32-4907-ab07-e030fb16fa5d.png)

2023-02-22 10:45 UTC, hanzlamateen commented
The tooltip of `AvatarPreview` control is not working when test in `AvatarSelectMenu.tsx` file. As shown below

![image](https://user-images.githubusercontent.com/10975502/220597470-24bc99d0-cceb-4db5-9bb7-3aa2dab7c2d7.png)

2023-02-22 17:44 UTC, speigg commented
@barankyle  @hanzlamateen thanks for the thorough review! 

It appears that this PR depends on another one https://github.com/XRFoundation/XREngine/pull/7614

So, let's get that other PR reviewed and merged in first, as some of the issues we are seeing here may originate in the React Router upgrade.

2023-02-22 20:03 UTC, jerknose commented
> On running `npm run predeploy` I am getting some errors and failed tests. Is this normal?
> 
> Also how to run storybook on my end. I tried running `npm run storybook` from `packages/ui` folder after running above command and getting error. My node version is `v19.6.0` and I am running WSL2 on Windows 11.
> 
> ```
> Snapshot Summary
>  › 69 snapshots written from 69 test suites.
> 
> Test Suites: 2 failed, 69 passed, 71 total
> Tests:       69 passed, 69 total
> Snapshots:   69 written, 69 total
> Time:        294.283 s
> Ran all test suites.
> Test results written to: tests/jest-test-results.json
> 
> > @xrengine/ui@0.0.1 build:storybook
> > build-storybook -c .storybook -o build/
> 
> info @storybook/react v6.5.16
> info
> info => Cleaning outputDir: /home/hanzlamateen/xrengine/packages/ui/build/
> info => Loading presets
> info => Compiling manager..
> node:internal/crypto/hash:71
>   this[kHandle] = new _Hash(algorithm, xofLen);
>                   ^
> 
> Error: error:0308010C:digital envelope routines::unsupported
>     at new Hash (node:internal/crypto/hash:71:19)
>     at Object.createHash (node:crypto:140:10)
>     at module.exports (/home/hanzlamateen/xrengine/node_modules/webpack/lib/util/createHash.js:135:53)
>     at NormalModule._initBuildHash (/home/hanzlamateen/xrengine/node_modules/webpack/lib/NormalModule.js:417:16)
>     at handleParseError (/home/hanzlamateen/xrengine/node_modules/webpack/lib/NormalModule.js:471:10)
>     at /home/hanzlamateen/xrengine/node_modules/webpack/lib/NormalModule.js:503:5
>     at /home/hanzlamateen/xrengine/node_modules/webpack/lib/NormalModule.js:358:12
>     at /home/hanzlamateen/xrengine/node_modules/loader-runner/lib/LoaderRunner.js:373:3
>     at iterateNormalLoaders (/home/hanzlamateen/xrengine/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
>     at Array.<anonymous> (/home/hanzlamateen/xrengine/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
>     at Storage.finished (/home/hanzlamateen/xrengine/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
>     at /home/hanzlamateen/xrengine/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
>     at /home/hanzlamateen/xrengine/node_modules/graceful-fs/graceful-fs.js:123:16
>     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
>   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
>   library: 'digital envelope routines',
>   reason: 'unsupported',
>   code: 'ERR_OSSL_EVP_UNSUPPORTED'
> }
> 
> Node.js v19.6.0
> npm ERR! Lifecycle script `build:storybook` failed with error:
> npm ERR! Error: command failed
> npm ERR!   in workspace: @xrengine/ui@0.0.1
> npm ERR!   at location: /home/hanzlamateen/xrengine/packages/ui
> npm ERR! Lifecycle script `predeploy` failed with error:
> npm ERR! Error: command failed
> npm ERR!   in workspace: @xrengine/ui@0.0.1
> npm ERR!   at location: /home/hanzlamateen/xrengine/packages/ui
> ```

This is most likely an incompatibly with Node / openssl. I'm on version 16. Newer versions are much more strict on allowing insecure servers. There's a --openssl-legacy-provider flag to ignore this.

2023-02-24 00:00 UTC, speigg approved these changes

2023-02-24 00:12 UTC, barankyle approved these changes

2023-02-24 00:12 UTC, barankyle approved these changes

2023-02-24 00:46 UTC, merged